name: "RNDash_Smoke"

# Triggers the workflow only when a pull request is successfully merged into main
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  Run-DAI-Test-Configuration:
    if: github.event.pull_request.merged == true # Ensures the PR was actually merged, not just closed
    strategy: 
      max-parallel: 1 
      matrix:
        os: [windows-latest] 
    runs-on: ${{ matrix.os }} 
    name: Run Test Configuration
    steps:
      - run: echo "Trigger event.. ${{ github.event_name }}. Runner OS.. ${{ runner.os }}."
      - name: Eggplant Runner
        uses: keysight-eggplant/eggplant-github-action@v1.0.22
        with:
          serverURL: "https://davita.corp" 
          testConfigID: "e9ad7b93-4e6d-4dcc-a2bb-dcfae2ea19d5" 
          clientID: "client:dai:api:integration:92eb9faf-7149-45e2-ad06-a854c29ec853" 
          clientSecret: "SzPuiy2TiSURYDOuXkVPaTn30C7lgXep" 
